#!/usr/bin/env python3
"""Build context/USL_CONTEXT_SNAPSHOT.md from the USL context source files.

Standard library only. Repo-local: reads a fixed set of files under context/ and
writes the snapshot. Does NOT scan the whole drive, raw-data folders, or any
controlled folder.

Sources:
  - context/USL_MEMORY_LEDGER.md   (selected sections)
  - context/USL_ACTIVE_TASKS.md    (full)
  - context/USL_FILE_INDEX.md      (row count + reference)
  - context/handoffs/              (latest handoff, if present)

Usage:
  python scripts/build_context_snapshot.py
"""

from __future__ import annotations

import datetime
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTEXT = REPO_ROOT / "context"
LEDGER = CONTEXT / "USL_MEMORY_LEDGER.md"
TASKS = CONTEXT / "USL_ACTIVE_TASKS.md"
FILE_INDEX = CONTEXT / "USL_FILE_INDEX.md"
HANDOFFS = CONTEXT / "handoffs"
SNAPSHOT = CONTEXT / "USL_CONTEXT_SNAPSHOT.md"

# Ledger H2 sections pulled into the snapshot, in order.
LEDGER_SECTIONS = ["CRM/GCC gates", "Security restrictions", "Human approval gates"]


def read_text(path: pathlib.Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def extract_section(markdown: str, heading: str) -> str:
    """Return the body under an H2 '## heading' up to the next H2 (exclusive)."""
    lines = markdown.splitlines()
    out: list[str] = []
    capturing = False
    for line in lines:
        if line.startswith("## "):
            if capturing:
                break
            capturing = line[3:].strip() == heading
            continue
        if capturing:
            out.append(line)
    return "\n".join(out).strip("\n")


def latest_handoff() -> pathlib.Path | None:
    if not HANDOFFS.is_dir():
        return None
    candidates = [
        p
        for p in HANDOFFS.iterdir()
        if p.is_file() and p.suffix == ".md" and p.name.lower() != "readme.md"
    ]
    if not candidates:
        return None
    # Sort by filename (dated names sort chronologically), then mtime as tiebreak.
    return sorted(candidates, key=lambda p: (p.name, p.stat().st_mtime))[-1]


def count_index_rows(markdown: str) -> int:
    count = 0
    for line in markdown.splitlines():
        s = line.strip()
        if not s.startswith("|"):
            continue
        if set(s) <= set("|-: "):  # separator row
            continue
        if s.startswith("| File or folder"):  # header row
            continue
        count += 1
    return count


def build() -> str:
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    ledger = read_text(LEDGER)
    tasks = read_text(TASKS)
    index = read_text(FILE_INDEX)
    handoff = latest_handoff()

    parts: list[str] = []
    parts.append("# USL Context Snapshot")
    parts.append("")
    parts.append(
        f"> Generated by `scripts/build_context_snapshot.py` on {now}. "
        "Do not edit by hand — edit the source files in `context/` and rebuild."
    )
    parts.append("")
    parts.append(
        "Current USL operating posture, assembled from the memory ledger, active "
        "tasks, file index, and latest handoff. This is a working snapshot; the "
        "system of record is the CRM/database, then the repo context files, then "
        "Google Drive."
    )
    parts.append("")

    for heading in LEDGER_SECTIONS:
        body = extract_section(ledger, heading)
        parts.append(f"## {heading}")
        parts.append("")
        parts.append(body if body else "_(section not found in USL_MEMORY_LEDGER.md)_")
        parts.append("")

    parts.append("## Active tasks")
    parts.append("")
    parts.append(
        tasks.strip() if tasks.strip() else "_(USL_ACTIVE_TASKS.md not found)_"
    )
    parts.append("")

    parts.append("## File index")
    parts.append("")
    if index.strip():
        parts.append(
            f"{count_index_rows(index)} indexed files/folders. See "
            "`context/USL_FILE_INDEX.md` for the full index, sensitivity, and "
            "AI-upload safety."
        )
    else:
        parts.append("_(USL_FILE_INDEX.md not found)_")
    parts.append("")

    parts.append("## Latest handoff")
    parts.append("")
    if handoff is not None:
        parts.append(f"`context/handoffs/{handoff.name}`")
        parts.append("")
        snippet = "\n".join(read_text(handoff).splitlines()[:20]).strip()
        if snippet:
            parts.append("```markdown")
            parts.append(snippet)
            parts.append("```")
    else:
        parts.append("_(no handoff files yet — see `context/handoffs/README.md`)_")
    parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    if not CONTEXT.is_dir():
        print(f"ERROR: context directory not found: {CONTEXT}", file=sys.stderr)
        return 1
    SNAPSHOT.write_text(build(), encoding="utf-8")
    print(f"Wrote {SNAPSHOT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
